Feature branch
kaizipaul/portfolio-project pull request #1
Opened 2022-08-18 15:36 UTC by kaizipaul

In this PR:
-- Added Linters
-- Added HTML file
-- Added CSS file
-- Created Header and Headline elements on HTML file
-- Styling the Header and Headline elements using CSS 

**Thank you for reviewing my PR**

2022-08-18 18:21 UTC, Abenezer-Tilahun requested changes
Hi @kaizipaul , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional README
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 18:21 UTC, Abenezer-Tilahun commented on index.html
> +    </header>
- [x] Good job for using `header` section for toolbar container. But for logo Please try to use  `a` tag for link and for hamburger button also use  a `nav` tag.
- [x] Good job for designing toolbar section to have the proper background image just like Figma design.

2022-08-18 18:21 UTC, Abenezer-Tilahun commented on index.html
> +        </div>
- [x] For Headline section kindly use  a `section` tag for container instead of `div` tag.
- [x] For the  main title ("Hey There. I'm Kai") kindly use  a `h1` tag and for subtitle ("I'm a Software Developer") uses a `header` tag `hx` (examples: `h1,h2` etc...) instead of `p` tag.
- [x] Good job for designing Headline section to have the proper background image just like Figma design.

2022-08-18 18:21 UTC, Abenezer-Tilahun commented on index.html
> +        </div>
- [ ] For  list of Social  icons kindly  uses a `ul` tag to group them, and `li` per icon; each icon has a link `a` tag to let you connect your social networks with the icons, using `href.`
- [ ] For Social icons please try to follow the Figma design Requirement .You must stick to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)
For Social icons your project look likes this : 
![try](https://user-images.githubusercontent.com/93598189/185462913-03b2d14c-2abf-477f-9d15-9ebf55b03d9d.PNG)

But Figma design Look like this : 

![fig](https://user-images.githubusercontent.com/93598189/185463345-06c6d033-2718-4366-a4b3-2acaf98295db.PNG)

2022-08-18 18:21 UTC, Abenezer-Tilahun commented on index.html
> +</html>
- Please try to  align the elements according to the requirement, you should use Flex-box in all 2 sections(toolbar and headline section.)
- Both toolbar and headline section must have the margins (top, bottom, left, right) defined in the Template design.
-  You didn't follow the Figma design Requirement, You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

Your project looks like this : 
![C](https://user-images.githubusercontent.com/93598189/185464024-c539d836-94c4-4ba0-adcc-13133ea61fb3.PNG)
Figma design Look likes : 
![Fi](https://user-images.githubusercontent.com/93598189/185464311-a9546eab-a708-4f55-bf77-0d43666a646a.PNG)

2022-08-18 18:21 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] You didn't follow the Figma design Requirement, You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)
- [ ] For Minimum mobile screen size should at 375px. But Your  paragraph("small text" ) is not fully visible and responsive . Kindly fix it.
Your Headline section Look likes : 
![h](https://user-images.githubusercontent.com/93598189/185465547-916a398f-0b68-4e49-a5ee-6049c08f7737.PNG)

Figma Headline section look likes : 

![Fi](https://user-images.githubusercontent.com/93598189/185466122-f560ea44-af8b-4df1-9fd6-a3b50867f22e.PNG)

2022-08-19 14:47 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @kaizipaul , 

Great work on making the changes requested by a previous reviewer 👏👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

 ## Required Changes ♻️

- [x] Kindly fix the margins, colors, and spacing between elements to match the Figma Design as described by the previous reviewer:

Your design:
![image](https://user-images.githubusercontent.com/73714615/185644518-91d7b155-3841-487b-abe1-beab5e8ff974.png)

Figma design:
![image](https://user-images.githubusercontent.com/73714615/185644608-acdd5419-c140-4fd2-a310-4a9876cb84f1.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 19:35 UTC, frank1738 approved these changes
Hi @kaizipaul , 

Good work implementing changes requested and coming up with a good design!.  Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 20:14 UTC, merged